services:
  plex-playlist:
    build: .
    container_name: plex-playlist
    ports:
      - "8080:80"
    volumes:
      - ./database:/var/www/html/database
      - ./logs:/var/www/html/logs
      - type: bind
        source: ./.env
        target: /var/www/html/.env
        bind:
          create_host_path: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
